# Generated by Django 4.0.6 on 2022-07-28 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_placed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('amount_paid', models.IntegerField()),
                ('py_mode', models.CharField(max_length=200)),
                ('order_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
